// src/components/ProjectGrid.vue
<template>
  <div class="space-y-6">
    <!-- 特色卡片（独占一行） -->
    <template v-for="(project, index) in projects" :key="project.id">
      <ProjectCard v-if="index < (featuredCount ?? 3)" :project="project" :featured="true" />
    </template>

    <!-- 其余项目使用网格布局（普通卡片） -->
    <div
      v-if="projects.length > (featuredCount ?? 3)"
      class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6"
    >
      <ProjectCard
        v-for="project in projects.slice(featuredCount ?? 3)"
        :key="project.id"
        :project="project"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import ProjectCard from './ProjectCard.vue'
import type { Project } from '../types'

const props = defineProps<{
  projects: Project[]
  featuredCount?: number
}>()
</script>

// src/components/ProjectGrid.tsx
import type { Project } from '@/types'
import ProjectCard from '@/components/ProjectCard'

interface ProjectGridProps {
  projects: Project[]
}

const ProjectGrid = ({ projects }: ProjectGridProps) => {
  if (projects.length === 0) {
    return (
      <div className="flex items-center justify-center py-32">
        <p className="font-display text-lg" style={{ color: 'var(--text-muted)' }}>
          暂无项目
        </p>
      </div>
    )
  }

  const featured = projects[0]
  const rest = projects.slice(1)

  return (
    <div className="space-y-8 sm:space-y-10">
      {/* Featured project — full width, cover-as-background */}
      <div className="w-full">
        <ProjectCard project={featured} index={0} variant="featured" />
      </div>

      {/* Rest projects — simple list */}
      {rest.length > 0 && (
        <div className="space-y-3 sm:space-y-4">
          {rest.map((project, i) => (
            <ProjectCard key={project.id} project={project} index={i + 1} variant="list" />
          ))}
        </div>
      )}
    </div>
  )
}

export default ProjectGrid
