// src/components/ProjectCard.tsx
import { motion } from 'framer-motion'
import type { Project } from '@/types'

interface ProjectCardProps {
  project: Project
  index: number
  variant: 'featured' | 'list'
}

const ProjectCard = ({ project, index, variant }: ProjectCardProps) => {
  const isFeatured = variant === 'featured'
  const hasUrl = project.url && project.url.length > 0

  // Featured: cover as background with overlay
  const featuredContent = (
    <div className="relative overflow-hidden h-full flex flex-col" style={{ minHeight: '360px' }}>
      {/* Cover as full background */}
      {project.cover ? (
        <div className="absolute inset-0">
          <img
            src={project.cover}
            alt=""
            className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-[1.02]"
          />
          {/* Gradient overlay */}
          <div className="absolute inset-0" style={{
            background: 'linear-gradient(to right, rgba(12,10,18,0.75) 0%, rgba(12,10,18,0.45) 50%, rgba(12,10,18,0.2) 100%)'
          }} />
        </div>
      ) : (
        <div className="absolute inset-0" style={{
          background: 'linear-gradient(135deg, rgba(247,131,172,0.15), rgba(247,131,172,0.05))'
        }} />
      )}

      {/* Content on top */}
      <div className="relative z-10 p-8 sm:p-10 flex flex-col justify-between flex-1">
        {/* Top: Title + Description */}
        <div>
          <h2
            className="font-display text-3xl sm:text-4xl font-semibold mb-3 leading-tight"
            style={{ color: '#f0ece4' }}
          >
            {project.name}
          </h2>
          <p className="text-sm leading-relaxed max-w-xl" style={{ color: 'rgba(240,236,228,0.8)' }}>
            {project.description}
          </p>
        </div>

        {/* Bottom: Tags + Meta */}
        <div className="space-y-4">
          {(project.tags?.length > 0 || project.status) && (
            <div className="flex flex-wrap items-center gap-2">
              {project.tags?.map((tag) => (
                <span
                  key={tag}
                  className="text-[0.65rem] px-2.5 py-1"
                  style={{
                    color: 'rgba(240,236,228,0.85)',
                    border: '0.5px solid rgba(240,236,228,0.25)',
                    background: 'rgba(240,236,228,0.1)',
                    backdropFilter: 'blur(4px)',
                  }}
                >
                  {tag}
                </span>
              ))}
              {project.status && (
                <span
                  className="text-[0.65rem] px-2.5 py-1"
                  style={{
                    color: 'var(--accent-pink)',
                    border: '0.5px solid rgba(247,131,172,0.3)',
                    background: 'rgba(247,131,172,0.1)',
                    backdropFilter: 'blur(4px)',
                  }}
                >
                  {project.status}
                </span>
              )}
            </div>
          )}

          {(project.version || (project.updatedAt && project.updatedAt !== '-')) && (
            <div className="flex gap-4">
              {project.version && (
                <span className="text-[0.6rem] uppercase tracking-widest" style={{ color: 'rgba(240,236,228,0.5)' }}>
                  {project.version}
                </span>
              )}
              {project.updatedAt && project.updatedAt !== '-' && (
                <span className="text-[0.6rem] uppercase tracking-widest" style={{ color: 'rgba(240,236,228,0.5)' }}>
                  {project.updatedAt}
                </span>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  )

  // List: simple card
  const listContent = (
    <div className="flex flex-col h-full p-6 sm:p-8">
      <h2
        className="font-display text-xl font-semibold mb-1"
        style={{ color: 'var(--text-primary)' }}
      >
        {project.name}
      </h2>
      <p className="text-sm leading-relaxed mb-3" style={{ color: 'var(--text-secondary)' }}>
        {project.description}
      </p>
      {(project.tags?.length > 0 || project.status) && (
        <div className="flex flex-wrap items-center gap-1.5 mb-3">
          {project.tags?.map((tag, i) => {
            const rotation = i % 3 === 0 ? '-1deg' : i % 3 === 1 ? '1deg' : '0deg'
            return (
              <span
                key={tag}
                className="text-[0.65rem] px-2 py-0.5 select-none"
                style={{
                  color: 'var(--text-muted)',
                  border: '0.5px solid rgba(44,42,48,0.12)',
                  background: 'transparent',
                  transform: `rotate(${rotation})`,
                }}
              >
                {tag}
              </span>
            )
          })}
          {project.status && (
            <span
              className="text-[0.65rem] px-2 py-0.5 select-none"
              style={{
                color: 'var(--accent-pink)',
                border: '0.5px solid rgba(44,42,48,0.12)',
                background: 'transparent',
                transform: 'rotate(-1deg)',
              }}
            >
              {project.status}
            </span>
          )}
        </div>
      )}
      {(project.version || (project.updatedAt && project.updatedAt !== '-')) && (
        <div className="flex gap-4 mt-auto">
          {project.version && (
            <span className="text-[0.6rem] uppercase tracking-widest" style={{ color: 'var(--text-muted)' }}>
              {project.version}
            </span>
          )}
          {project.updatedAt && project.updatedAt !== '-' && (
            <span className="text-[0.6rem] uppercase tracking-widest" style={{ color: 'var(--text-muted)' }}>
              {project.updatedAt}
            </span>
          )}
        </div>
      )}
    </div>
  )

  const motionProps = {
    className: 'group block h-full',
    style: {
      background: isFeatured ? 'transparent' : 'var(--bg-card)',
      border: isFeatured ? 'none' : '0.5px solid var(--border-line)',
      minHeight: isFeatured ? '360px' : undefined,
    },
    initial: { opacity: 0, y: 16 },
    whileInView: { opacity: 1, y: 0 },
    viewport: { once: true },
    transition: { duration: 0.6, delay: isFeatured ? 0 : index * 0.08 },
    whileHover: isFeatured
      ? { y: -3, transition: { duration: 0.12 } }
      : { y: -3, boxShadow: '0 0 20px rgba(247, 131, 172, 0.1)', transition: { duration: 0.12 } },
  }

  const inner = isFeatured ? featuredContent : listContent

  if (hasUrl) {
    return (
      <motion.a href={project.url} target="_blank" rel="noopener noreferrer" {...motionProps}>
        {inner}
      </motion.a>
    )
  }

  return (
    <motion.div {...motionProps}>
      {inner}
    </motion.div>
  )
}

export default ProjectCard

// src/components/ProjectCard.vue
<template>
  <div 
    class="glass-card reveal-on-scroll overflow-hidden cursor-pointer group flex flex-col h-full"
    style="position:relative;z-index:1"
    @click="openProject"
  >
    <!-- 封面图区域 -->
    <div v-if="project.cover" class="h-48 bg-gradient-to-br from-primary-light to-purple-light overflow-hidden">
      <img 
        :src="project.cover" 
        :alt="project.name"
        class="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110"
      />
    </div>
    <!-- 无封面时的渐变背景 -->
    <div v-else class="h-32 bg-gradient-to-br from-primary-pink/20 to-primary-purple/20 flex items-center justify-center">
      <span class="text-4xl opacity-50">✨</span>
    </div>

    <!-- 项目信息 -->
    <div class="p-5 flex-1 flex flex-col">
      <!-- 项目名称和状态 -->
      <div class="flex items-start justify-between mb-3 gap-2">
        <h3 class="text-lg font-bold text-text-primary leading-tight group-hover:text-gradient transition-all duration-300">{{ project.name }}</h3>
        <span 
          :class="statusClass"
          class="px-2.5 py-1 text-xs font-medium rounded-full whitespace-nowrap status-badge"
        >
          {{ project.status }}
        </span>
      </div>

      <!-- 项目描述 -->
      <p class="text-text-body text-sm mb-4 line-clamp-2 leading-relaxed flex-1 font-normal">{{ project.description }}</p>

      <!-- 标签 -->
      <div class="flex flex-wrap gap-2 mb-4">
        <span 
          v-for="tag in project.tags" 
          :key="tag"
          class="px-2.5 py-1 bg-gradient-to-r from-primary-purple/10 to-primary-pink/10 text-primary-purple text-xs rounded-full border border-primary-purple/20 font-medium"
        >
          {{ tag }}
        </span>
      </div>

      <!-- 版本和更新时间 - 固定在底部 -->
      <div class="flex items-center justify-between text-xs text-text-secondary pt-3 border-t border-gray-100 mt-auto font-normal">
        <span v-if="project.version">{{ project.version }}</span>
        <span v-if="project.updatedAt" class="flex items-center gap-1">
          <svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"></path>
          </svg>
          {{ project.updatedAt }}
        </span>
      </div>
    </div>
    
    <!-- 悬停时的光效装饰 -->
    <div class="absolute inset-0 pointer-events-none opacity-0 group-hover:opacity-100 transition-opacity duration-500">
      <div class="absolute -top-20 -right-20 w-40 h-40 bg-primary-pink/10 rounded-full blur-3xl"></div>
      <div class="absolute -bottom-20 -left-20 w-40 h-40 bg-primary-purple/10 rounded-full blur-3xl"></div>
    </div>
  </div>
</template>

<script setup>
import { computed } from 'vue'

const props = defineProps({
  project: {
    type: Object,
    required: true
  }
})

// 状态样式
const statusClass = computed(() => {
  const statusMap = {
    '开发中': 'bg-gradient-to-r from-primary-pink/20 to-primary-pink/10 text-primary-dark border border-primary-pink/30',
    '已上线': 'bg-gradient-to-r from-primary-purple/20 to-primary-purple/10 text-primary-purple border border-primary-purple/30',
    '已下线': 'bg-gray-100 text-text-secondary border border-gray-200'
  }
  return statusMap[props.project.status] || 'bg-gray-100 text-gray-800 border border-gray-200'
})

// 打开项目链接
const openProject = () => {
  if (props.project.url) {
    window.open(props.project.url, '_blank')
  }
}
</script>
